// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `summary`

Future<LocalVault> start({
  required String dataDir,
  required String pluginsDir,
}) => RustLib.instance.api.crateApiLocalStart(
  dataDir: dataDir,
  pluginsDir: pluginsDir,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>>
abstract class LocalVault implements RustOpaqueInterface {
  Future<List<SourceSummary>> listSources();

  Future<List<WorkSummary>> searchSource({
    required String sourceId,
    required String query,
    required int page,
  });
}

class SourceSummary {
  final String id;
  final String name;
  final String version;
  final String kind;

  const SourceSummary({
    required this.id,
    required this.name,
    required this.version,
    required this.kind,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ version.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          version == other.version &&
          kind == other.kind;
}

class WorkSummary {
  final String title;
  final String remoteUrl;
  final String? coverUrl;

  const WorkSummary({
    required this.title,
    required this.remoteUrl,
    this.coverUrl,
  });

  @override
  int get hashCode => title.hashCode ^ remoteUrl.hashCode ^ coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkSummary &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          remoteUrl == other.remoteUrl &&
          coverUrl == other.coverUrl;
}
