//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "chapters")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(unique_key = "idx_chapters_work_remote")]
	pub work_id: Uuid,
	pub title: String,
	#[sea_orm(unique_key = "idx_chapters_work_remote")]
	pub remote_url: String,
	pub sort_index: i64,
	pub content_kind: String,
	pub scanlation_group: Option<String>,
	pub released_at: Option<DateTimeWithTimeZone>,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::reading_progress::Entity")]
	ReadingProgress,
	#[sea_orm(
		belongs_to = "super::works::Entity",
		from = "Column::WorkId",
		to = "super::works::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Works,
}

impl Related<super::reading_progress::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ReadingProgress.def()
	}
}

impl Related<super::works::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Works.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
