//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod categories;
pub mod chapters;
pub mod glossary_entries;
pub mod glossary_meanings;
pub mod glossary_votes;
pub mod invite_codes;
pub mod jobs;
pub mod library_entries;
pub mod reading_progress;
pub mod server_settings;
pub mod sessions;
pub mod sources;
pub mod translation_cache;
pub mod user_settings;
pub mod users;
pub mod works;
