//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod categories;
pub mod chapters;
pub mod jobs;
pub mod library_entries;
pub mod reading_progress;
pub mod sessions;
pub mod sources;
pub mod users;
pub mod works;
