//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reading_progress")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(unique_key = "idx_progress_user_chapter")]
	pub user_id: Uuid,
	pub work_id: Uuid,
	#[sea_orm(unique_key = "idx_progress_user_chapter")]
	pub chapter_id: Uuid,
	pub read_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::chapters::Entity",
		from = "Column::ChapterId",
		to = "super::chapters::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Chapters,
	#[sea_orm(
		belongs_to = "super::users::Entity",
		from = "Column::UserId",
		to = "super::users::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Users,
}

impl Related<super::chapters::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Chapters.def()
	}
}

impl Related<super::users::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Users.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
