//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sources")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub name: String,
	pub version: String,
	pub kind: String,
	pub icon_url: Option<String>,
	pub referer_url: Option<String>,
	pub base_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::works::Entity")]
	Works,
}

impl Related<super::works::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Works.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
