//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(unique)]
	pub username: String,
	pub password_hash: String,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::categories::Entity")]
	Categories,
	#[sea_orm(has_many = "super::library_entries::Entity")]
	LibraryEntries,
	#[sea_orm(has_many = "super::reading_progress::Entity")]
	ReadingProgress,
	#[sea_orm(has_many = "super::sessions::Entity")]
	Sessions,
}

impl Related<super::categories::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Categories.def()
	}
}

impl Related<super::library_entries::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::LibraryEntries.def()
	}
}

impl Related<super::reading_progress::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ReadingProgress.def()
	}
}

impl Related<super::sessions::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Sessions.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
