//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "works")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub kind: String,
	#[sea_orm(unique_key = "idx_works_remote_identity")]
	pub source_id: String,
	#[sea_orm(unique_key = "idx_works_remote_identity")]
	pub remote_url: String,
	pub title: String,
	pub cover_url: Option<String>,
	pub alternative_names: Option<Json>,
	pub authors: Option<Json>,
	pub artists: Option<Json>,
	pub status: Option<String>,
	pub release_date: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	pub genres: Option<Json>,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::chapters::Entity")]
	Chapters,
	#[sea_orm(has_many = "super::library_entries::Entity")]
	LibraryEntries,
	#[sea_orm(
		belongs_to = "super::sources::Entity",
		from = "Column::SourceId",
		to = "super::sources::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Sources,
}

impl Related<super::chapters::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Chapters.def()
	}
}

impl Related<super::library_entries::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::LibraryEntries.def()
	}
}

impl Related<super::sources::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Sources.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
