[package]
name = "manga-vault"
version = "0.17.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["api", "config", "database/*", "scrappers"]

[dependencies]
api = { path = "api" }
tokio = { version = "1", features = ["full"] }
