[package]
name = "manga-vault"
version = "0.18.6"
edition = "2024"

[[bin]]
name = "manga-vault"
path = "src/main.rs"

[workspace]
members = ["apps/http/*","config", "database/*", "scrapers/scraper_core", "scrapers/scraper_types"]

[dependencies]
config = { path = "config" }
connection = { path = "database/connection" }
scraper_core = { path = "scrapers/scraper_core" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3.0"
http-utils = { path = "apps/http/utils" }
gql-api = { path = "apps/http/gql" }