imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
group_imports = "StdExternalCrate"
wrap_comments = false
style_edition = "2024"
format_macro_matchers = true
reorder_impl_items = true
max_width = 125
struct_variant_width = 0
hard_tabs = true
