[package]
name = "http-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
config = { path = "../../../config" }
zip = "2.1.5"