[package]
name = "manga_dex"
version = "0.2.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
scraper_types = { path = "../scraper_types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
isahc = "1.7"
once_cell = "1.21"
