[package]
name = "manga_dex"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
scraper_types = { path = "../scraper_types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
isahc = "1.7"
once_cell = "1.20"
