//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "chapters")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub title: String,
	pub url: String,
	pub created_at: String,
	pub updated_at: String,
	pub manga_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::mangas::Entity",
		from = "Column::MangaId",
		to = "super::mangas::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Mangas,
	#[sea_orm(has_many = "super::read_chapters::Entity")]
	ReadChapters,
}

impl Related<super::mangas::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Mangas.def()
	}
}

impl Related<super::read_chapters::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ReadChapters.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
