//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "favorite_mangas")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub user_id: i32,
	pub manga_id: i32,
	pub categorie_id: i32,
	pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "Entity",
		from = "Column::Id",
		to = "Column::CategorieId",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	SelfRef3,
	#[sea_orm(
		belongs_to = "Entity",
		from = "Column::Id",
		to = "Column::MangaId",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	SelfRef2,
	#[sea_orm(
		belongs_to = "Entity",
		from = "Column::Id",
		to = "Column::UserId",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	SelfRef1,
}

impl ActiveModelBehavior for ActiveModel {}
