//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod categories;
pub mod chapters;
pub mod favorite_mangas;
pub mod files;
pub mod mangas;
pub mod read_chapters;
pub mod temp;
pub mod users;
