//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14
#![allow(unused_imports)]
pub use super::categories::Entity as Categories;
pub use super::chapters::Entity as Chapters;
pub use super::favorite_mangas::Entity as FavoriteMangas;
pub use super::files::Entity as Files;
pub use super::mangas::Entity as Mangas;
pub use super::read_chapters::Entity as ReadChapters;
pub use super::users::Entity as Users;
