// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
	non_camel_case_types,
	unused,
	non_snake_case,
	clippy::needless_return,
	clippy::redundant_closure_call,
	clippy::redundant_closure,
	clippy::useless_conversion,
	clippy::unit_arg,
	clippy::unused_unit,
	clippy::double_parens,
	clippy::let_and_return,
	clippy::too_many_arguments,
	clippy::match_single_binding,
	clippy::clone_on_copy,
	clippy::let_unit_value,
	clippy::deref_addrof,
	clippy::explicit_auto_deref,
	clippy::borrow_deref_ref,
	clippy::uninlined_format_args,
	clippy::needless_borrow
)]

// Section: imports

use crate::api::local::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
	default_stream_sink_codec = SseCodec,
	default_rust_opaque = RustOpaqueMoi,
	default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -2119521408;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__local__LocalVault_list_sources_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "LocalVault_list_sources",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that = <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>>>::sse_decode(
				&mut deserializer,
			);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, ()>(
					(move || async move {
						let mut api_that_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let output_ok =
							Result::<_, ()>::Ok(crate::api::local::LocalVault::list_sources(&*api_that_guard).await)?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__api__local__LocalVault_search_source_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "LocalVault_search_source",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_that = <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>>>::sse_decode(
				&mut deserializer,
			);
			let api_source_id = <String>::sse_decode(&mut deserializer);
			let api_query = <String>::sse_decode(&mut deserializer);
			let api_page = <u32>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
					(move || async move {
						let mut api_that_guard = None;
						let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
							flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false),
						]);
						for i in decode_indices_ {
							match i {
								0 => api_that_guard = Some(api_that.lockable_decode_async_ref().await),
								_ => unreachable!(),
							}
						}
						let api_that_guard = api_that_guard.unwrap();
						let output_ok = crate::api::local::LocalVault::search_source(
							&*api_that_guard,
							api_source_id,
							api_query,
							api_page,
						)
						.await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}
fn wire__crate__api__local__start_impl(
	port_: flutter_rust_bridge::for_generated::MessagePort,
	ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len_: i32,
	data_len_: i32,
) {
	FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
		flutter_rust_bridge::for_generated::TaskInfo {
			debug_name: "start",
			port: Some(port_),
			mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
		},
		move || {
			let message = unsafe {
				flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
			};
			let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
			let api_data_dir = <String>::sse_decode(&mut deserializer);
			let api_plugins_dir = <String>::sse_decode(&mut deserializer);
			deserializer.end();
			move |context| async move {
				transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
					(move || async move {
						let output_ok = crate::api::local::start(api_data_dir, api_plugins_dir).await?;
						Ok(output_ok)
					})()
					.await,
				)
			}
		},
	)
}

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>);

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <String>::sse_decode(deserializer);
		return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
	}
}

impl SseDecode for LocalVault {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner =
			<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>>>::sse_decode(deserializer);
		return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
	}
}

impl SseDecode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <usize>::sse_decode(deserializer);
		return decode_rust_opaque_moi(inner);
	}
}

impl SseDecode for String {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut inner = <Vec<u8>>::sse_decode(deserializer);
		return String::from_utf8(inner).unwrap();
	}
}

impl SseDecode for Vec<u8> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut len_ = <i32>::sse_decode(deserializer);
		let mut ans_ = Vec::with_capacity(len_ as usize);
		for idx_ in 0..len_ {
			ans_.push(<u8>::sse_decode(deserializer));
		}
		return ans_;
	}
}

impl SseDecode for Vec<crate::api::local::SourceSummary> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut len_ = <i32>::sse_decode(deserializer);
		let mut ans_ = Vec::with_capacity(len_ as usize);
		for idx_ in 0..len_ {
			ans_.push(<crate::api::local::SourceSummary>::sse_decode(deserializer));
		}
		return ans_;
	}
}

impl SseDecode for Vec<crate::api::local::WorkSummary> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut len_ = <i32>::sse_decode(deserializer);
		let mut ans_ = Vec::with_capacity(len_ as usize);
		for idx_ in 0..len_ {
			ans_.push(<crate::api::local::WorkSummary>::sse_decode(deserializer));
		}
		return ans_;
	}
}

impl SseDecode for Option<String> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		if (<bool>::sse_decode(deserializer)) {
			return Some(<String>::sse_decode(deserializer));
		} else {
			return None;
		}
	}
}

impl SseDecode for crate::api::local::SourceSummary {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_id = <String>::sse_decode(deserializer);
		let mut var_name = <String>::sse_decode(deserializer);
		let mut var_version = <String>::sse_decode(deserializer);
		let mut var_kind = <String>::sse_decode(deserializer);
		return crate::api::local::SourceSummary {
			id: var_id,
			name: var_name,
			version: var_version,
			kind: var_kind,
		};
	}
}

impl SseDecode for u32 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_u32::<NativeEndian>().unwrap()
	}
}

impl SseDecode for u8 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_u8().unwrap()
	}
}

impl SseDecode for () {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
	}
}

impl SseDecode for crate::api::local::WorkSummary {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		let mut var_title = <String>::sse_decode(deserializer);
		let mut var_remoteUrl = <String>::sse_decode(deserializer);
		let mut var_coverUrl = <Option<String>>::sse_decode(deserializer);
		return crate::api::local::WorkSummary {
			title: var_title,
			remote_url: var_remoteUrl,
			cover_url: var_coverUrl,
		};
	}
}

impl SseDecode for i32 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_i32::<NativeEndian>().unwrap()
	}
}

impl SseDecode for bool {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
		deserializer.cursor.read_u8().unwrap() != 0
	}
}

fn pde_ffi_dispatcher_primary_impl(
	func_id: i32,
	port: flutter_rust_bridge::for_generated::MessagePort,
	ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len: i32,
	data_len: i32,
) {
	// Codec=Pde (Serialization + dispatch), see doc to use other codecs
	match func_id {
		1 => wire__crate__api__local__LocalVault_list_sources_impl(port, ptr, rust_vec_len, data_len),
		2 => wire__crate__api__local__LocalVault_search_source_impl(port, ptr, rust_vec_len, data_len),
		3 => wire__crate__api__local__start_impl(port, ptr, rust_vec_len, data_len),
		_ => unreachable!(),
	}
}

fn pde_ffi_dispatcher_sync_impl(
	func_id: i32,
	ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
	rust_vec_len: i32,
	data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
	// Codec=Pde (Serialization + dispatch), see doc to use other codecs
	match func_id {
		_ => unreachable!(),
	}
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<LocalVault> {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0).into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<LocalVault> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<LocalVault>> for LocalVault {
	fn into_into_dart(self) -> FrbWrapper<LocalVault> {
		self.into()
	}
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::local::SourceSummary {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		[
			self.id.into_into_dart().into_dart(),
			self.name.into_into_dart().into_dart(),
			self.version.into_into_dart().into_dart(),
			self.kind.into_into_dart().into_dart(),
		]
		.into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::local::SourceSummary {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::local::SourceSummary> for crate::api::local::SourceSummary {
	fn into_into_dart(self) -> crate::api::local::SourceSummary {
		self
	}
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::local::WorkSummary {
	fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
		[
			self.title.into_into_dart().into_dart(),
			self.remote_url.into_into_dart().into_dart(),
			self.cover_url.into_into_dart().into_dart(),
		]
		.into_dart()
	}
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::local::WorkSummary {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::local::WorkSummary> for crate::api::local::WorkSummary {
	fn into_into_dart(self) -> crate::api::local::WorkSummary {
		self
	}
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<String>::sse_encode(format!("{:?}", self), serializer);
	}
}

impl SseEncode for LocalVault {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>>>::sse_encode(
			flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self),
			serializer,
		);
	}
}

impl SseEncode for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		let (ptr, size) = self.sse_encode_raw();
		<usize>::sse_encode(ptr, serializer);
		<i32>::sse_encode(size, serializer);
	}
}

impl SseEncode for String {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<Vec<u8>>::sse_encode(self.into_bytes(), serializer);
	}
}

impl SseEncode for Vec<u8> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<i32>::sse_encode(self.len() as _, serializer);
		for item in self {
			<u8>::sse_encode(item, serializer);
		}
	}
}

impl SseEncode for Vec<crate::api::local::SourceSummary> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<i32>::sse_encode(self.len() as _, serializer);
		for item in self {
			<crate::api::local::SourceSummary>::sse_encode(item, serializer);
		}
	}
}

impl SseEncode for Vec<crate::api::local::WorkSummary> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<i32>::sse_encode(self.len() as _, serializer);
		for item in self {
			<crate::api::local::WorkSummary>::sse_encode(item, serializer);
		}
	}
}

impl SseEncode for Option<String> {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<bool>::sse_encode(self.is_some(), serializer);
		if let Some(value) = self {
			<String>::sse_encode(value, serializer);
		}
	}
}

impl SseEncode for crate::api::local::SourceSummary {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<String>::sse_encode(self.id, serializer);
		<String>::sse_encode(self.name, serializer);
		<String>::sse_encode(self.version, serializer);
		<String>::sse_encode(self.kind, serializer);
	}
}

impl SseEncode for u32 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
	}
}

impl SseEncode for u8 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_u8(self).unwrap();
	}
}

impl SseEncode for () {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_u64::<NativeEndian>(self as _).unwrap();
	}
}

impl SseEncode for crate::api::local::WorkSummary {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		<String>::sse_encode(self.title, serializer);
		<String>::sse_encode(self.remote_url, serializer);
		<Option<String>>::sse_encode(self.cover_url, serializer);
	}
}

impl SseEncode for i32 {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
	}
}

impl SseEncode for bool {
	// Codec=Sse (Serialization based), see doc to use other codecs
	fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
		serializer.cursor.write_u8(self as _).unwrap();
	}
}

#[cfg(not(target_family = "wasm"))]
mod io {
	// This file is automatically generated, so please do not edit it.
	// @generated by `flutter_rust_bridge`@ 2.12.0.

	// Section: imports

	use super::*;
	use crate::api::local::*;
	use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
	use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
	use flutter_rust_bridge::{Handler, IntoIntoDart};

	// Section: boilerplate

	flutter_rust_bridge::frb_generated_boilerplate_io!();

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_manga_vault_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalVault(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>>::increment_strong_count(ptr as _);
	}

	#[unsafe(no_mangle)]
	pub extern "C" fn frbgen_manga_vault_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalVault(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>>::decrement_strong_count(ptr as _);
	}
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
	// This file is automatically generated, so please do not edit it.
	// @generated by `flutter_rust_bridge`@ 2.12.0.

	// Section: imports

	use super::*;
	use crate::api::local::*;
	use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
	use flutter_rust_bridge::for_generated::wasm_bindgen;
	use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
	use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
	use flutter_rust_bridge::{Handler, IntoIntoDart};

	// Section: boilerplate

	flutter_rust_bridge::frb_generated_boilerplate_web!();

	#[wasm_bindgen]
	pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalVault(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>>::increment_strong_count(ptr as _);
	}

	#[wasm_bindgen]
	pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalVault(
		ptr: *const std::ffi::c_void,
	) {
		MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalVault>>::decrement_strong_count(ptr as _);
	}
}
#[cfg(target_family = "wasm")]
pub use web::*;
