CREATE TABLE Users (
  id INTEGER PRIMARY KEY,
  username TEXT UNIQUE,
  hashedPassword TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Manga (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  url TEXT,
  img TEXT,
  chaptersId INTEGER,
  readChaptersId INTEGER,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  userId INTEGER,
  FOREIGN KEY (userId) REFERENCES Users(id)
);
CREATE TRIGGER update_manga_timestamp
AFTER
UPDATE ON Manga BEGIN
UPDATE Manga
SET updatedAt = CURRENT_TIMESTAMP
WHERE id = NEW.id;
END;
CREATE TABLE Chapter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  url TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  mangaId INTEGER,
  FOREIGN KEY (mangaId) REFERENCES Manga(id)
);
CREATE TRIGGER update_chapter_timestamp
AFTER
UPDATE ON Chapter BEGIN
UPDATE Chapter
SET updatedAt = CURRENT_TIMESTAMP
WHERE id = NEW.id;
END;
CREATE TABLE FavoriteMangas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER,
  mangaId INTEGER,
  categorieId INTEGER,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id),
  FOREIGN KEY (mangaId) REFERENCES Manga(id),
  FOREIGN KEY (categorieId) REFERENCES Categories(id)
);
CREATE TABLE Categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  userId INTEGER,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id)
);
CREATE TABLE readChapters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER,
  chapterId INTEGER,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id),
  FOREIGN KEY (chapterId) REFERENCES Chapter(id)
);