[package]
name = "hari_manga"
version = "0.3.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
scraper = "0.23"
wit-bindgen = "0.43"
