[package]
name = "hari_manga"
version = "0.3.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
scraper = "0.24"
wit-bindgen = "0.44"
