[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.9"
once_cell = "1.21"
tracing = "0.1"
config-derive = { workspace = true }
config = "0.15"