//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "favorite_mangas")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub user_id: i32,
	pub manga_id: i32,
	pub category_id: i32,
	pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::categories::Entity",
		from = "Column::CategoryId",
		to = "super::categories::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Categories,
	#[sea_orm(
		belongs_to = "super::mangas::Entity",
		from = "Column::MangaId",
		to = "super::mangas::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Mangas,
	#[sea_orm(
		belongs_to = "super::users::Entity",
		from = "Column::UserId",
		to = "super::users::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Users,
}

impl Related<super::categories::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Categories.def()
	}
}

impl Related<super::mangas::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Mangas.def()
	}
}

impl Related<super::users::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Users.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
