//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod categories;
pub mod chapters;
pub mod favorite_mangas;
pub mod files;
pub mod manga_pack_members;
pub mod manga_packs;
pub mod mangas;
pub mod read_chapters;
pub mod temp;
pub mod users;
