//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "novels")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub title: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	pub scraper: String,
	pub url: String,
	pub status: Option<String>,
	pub updated_at: DateTime,
	pub img_url: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub alternative_names: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub authors: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub artists: Option<String>,
	pub novel_type: Option<String>,
	pub release_date: Option<DateTime>,
	#[sea_orm(column_type = "Text", nullable)]
	pub genres: Option<String>,
	pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::favorite_novels::Entity")]
	FavoriteNovels,
	#[sea_orm(has_many = "super::novel_chapters::Entity")]
	NovelChapters,
	#[sea_orm(has_many = "super::read_novel_chapters::Entity")]
	ReadNovelChapters,
}

impl Related<super::favorite_novels::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::FavoriteNovels.def()
	}
}

impl Related<super::novel_chapters::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::NovelChapters.def()
	}
}

impl Related<super::read_novel_chapters::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ReadNovelChapters.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
