//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "novel_chapters")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub novel_id: i32,
	pub title: String,
	pub url: String,
	pub created_at: DateTime,
	pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::novels::Entity",
		from = "Column::NovelId",
		to = "super::novels::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Novels,
	#[sea_orm(has_many = "super::read_novel_chapters::Entity")]
	ReadNovelChapters,
}

impl Related<super::novels::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Novels.def()
	}
}

impl Related<super::read_novel_chapters::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ReadNovelChapters.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
