//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "read_novel_chapters")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub user_id: i32,
	pub chapter_id: i32,
	pub novel_id: i32,
	pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::novel_chapters::Entity",
		from = "Column::ChapterId",
		to = "super::novel_chapters::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	NovelChapters,
	#[sea_orm(
		belongs_to = "super::novels::Entity",
		from = "Column::NovelId",
		to = "super::novels::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Novels,
	#[sea_orm(
		belongs_to = "super::users::Entity",
		from = "Column::UserId",
		to = "super::users::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Users,
}

impl Related<super::novel_chapters::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::NovelChapters.def()
	}
}

impl Related<super::novels::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Novels.def()
	}
}

impl Related<super::users::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Users.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
