//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub username: String,
	pub hashed_password: String,
	pub created_at: DateTime,
	pub image_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::categories::Entity")]
	Categories,
	#[sea_orm(has_many = "super::favorite_mangas::Entity")]
	FavoriteMangas,
	#[sea_orm(has_many = "super::files::Entity")]
	Files,
	#[sea_orm(has_many = "super::read_chapters::Entity")]
	ReadChapters,
}

impl Related<super::categories::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Categories.def()
	}
}

impl Related<super::favorite_mangas::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::FavoriteMangas.def()
	}
}

impl Related<super::files::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Files.def()
	}
}

impl Related<super::read_chapters::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ReadChapters.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
