[package]
name = "version-check"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = { workspace = true }
reqwest = { workspace = true }
semver = "1.0"
serde = { workspace = true }
thiserror = "2.0"
