[package]
name = "scrappers"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
scraper = "0.18"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }