[package]
name = "source-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
ammonia = { workspace = true }
async-trait = { workspace = true }
domain = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
url = { workspace = true }
