name: Upload Manga Vault Build to Release (Windows)

on:
  release:
    types: released

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  issues: write
  pull-requests: write
  security-events: write

jobs:
  build-and-upload-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/manga-vault.exe
          asset_name: manga-vault.exe
          asset_content_type: application/octet-stream
